export default Database = [
    {
        id: 1,
        title: ' #1 Reject control. Lane not ready',
        info: 'Please check this component...',
        date: '16/10/23',
        time: '13:21',
        country: 'Turkiye',
        customer: 'Customer A',
        site: 'Site 1',
        device: 'Device A',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#2dc937'
    },
    {
        id: 2,
        title: ' #2 Reject control. X-Ray warming up',
        info: 'Please check this component...',
        date: '16/10/23',
        time: '12:10',
        country: 'Bulgaria',
        customer: 'Customer B',
        site: 'Site 2',
        device: 'Device B',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#e7b416'
    },
    {
        id: 3,
        title: ' #3 Right belt cover is open',
        info: 'Please check this component...',
        date: '15/10/23',
        time: '18:13',
        country: 'Iceland',
        customer: 'Customer C',
        site: 'Site 3',
        device: 'Device C',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#2dc937'
    },
    {
        id: 4,
        title: ' #4 Belt running without X-Ray',
        info: 'Please check this component...',
        date: '15/10/23',
        time: '11:01',
        country: 'China',
        customer: 'Customer D',
        site: 'Site 4',
        device: 'Device D',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#cc3232'
    },
    {
        id: 5,
        title: ' #5 Emergency button pressed',
        info: 'Please check this component...',
        date: '15/10/23',
        time: '08:09',
        country: 'Spain',
        customer: 'Customer E',
        site: 'Site 5',
        device: 'Device E',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#e7b416'
    },
    {
        id: 6,
        title: " #6 'X-Ray enable' key switch in OFF position",
        info: 'Please check this component...',
        date: '14/10/23',
        time: '23:12',
        country: 'India',
        customer: 'Customer F',
        site: 'Site 6',
        device: 'Device F',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#2dc937'
    },
    {
        id: 7,
        title: ' #7 Reject control. Lane not ready',
        info: 'Please check this component...',
        date: '14/10/23',
        time: '19:19',
        country: 'France',
        customer: 'Customer G',
        site: 'Site 7',
        device: 'Device G',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#cc3232'
    },
    {
        id: 8,
        title: ' #8 Reject control. System in Alarm state',
        info: 'Please check this component...',
        date: '14/10/23',
        time: '17:15',
        country: 'USA',
        customer: 'Customer H',
        site: 'Site 8',
        device: 'Device H',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#e7b416'
    },
    {
        id: 9,
        title: ' #9 EDM fault',
        info: 'Please check this component...',
        date: '14/10/23',
        time: '13:00',
        country: 'Brazil',
        customer: 'Customer I',
        site: 'Site 9',
        device: 'Device I',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#e7b416'
    },
    {
        id: 10,
        title: ' #10 Motor cover open',
        info: 'Please check this component...',
        date: '13/10/23',
        time: '17:30',
        country: 'Germany',
        customer: 'Customer J',
        site: 'Site 10',
        device: 'Device J',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        color: '#2dc937'
    },
];